--<ScriptOptions statementTerminator=";"/>

ALTER TABLE RD4_TEMPORARY_AUTHORITY DROP CONSTRAINT RD4_TEMPORARY_AUTHORITY_FK_USER;

ALTER TABLE RD4_MAIN_AUTHORITY DROP CONSTRAINT RD4_MAIN_AUTHORITY_FK_USER;

ALTER TABLE RD4_SYSTEM_AUTHORITY DROP CONSTRAINT RD4_SYSTEM_AUTHORITY_FK_SYSTEM_FUNCTION;

ALTER TABLE RD4_SYSTEM_ADMIN DROP CONSTRAINT RD4_SYSTEM_ADMIN_FK_USER;

ALTER TABLE RD4_SYSTEM_AUTHORITY DROP CONSTRAINT RD4_SYSTEM_AUTHORITY_FK_ROLE;

ALTER TABLE RD4_MESSAGE DROP CONSTRAINT RD4_MESSAGE_FK_RECIEVER;

ALTER TABLE RD4_USER DROP CONSTRAINT RD4_USER_FK_ROLE;

ALTER TABLE RD4_TASK DROP CONSTRAINT RD4_TASK_FK_USER;

ALTER TABLE RD4_BUG_REPORT DROP CONSTRAINT RD4_BUG_REPORT_FK_SYSTEM;

ALTER TABLE RD4_BUG_REPORT DROP CONSTRAINT RD4_BUG_REPORT_FK_USER;

ALTER TABLE RD4_TASK DROP CONSTRAINT RD4_TASK_FK_CREATOR;

ALTER TABLE RD4_UPLOAD_FILE DROP CONSTRAINT RD4_UPLOAD_FILE_FK_USER;

ALTER TABLE RD4_DEPENDENT_SYSTEM DROP CONSTRAINT RD4_DEPENDENT_SYSTEM_FK_SYSTEM;

ALTER TABLE RD4_MESSAGE DROP CONSTRAINT RD4_MESSAGE_FK_SENDER;

ALTER TABLE RD4_MAIN_AUTHORITY DROP CONSTRAINT RD4_MAIN_AUTHORITY_FK_AUTHORITY;

ALTER TABLE RD4_TEMPORARY_AUTHORITY DROP CONSTRAINT RD4_TEMPORARY_AUTHORITY_FK_FUNCTION;

ALTER TABLE RD2_PERSON DROP CONSTRAINT PERSON_FK_ROLE;

ALTER TABLE RD4_SYSTEM_FUNCTION DROP CONSTRAINT RD4_SYSTEM_FUNCTION_FK_SYSTEM;

ALTER TABLE RD4_SYSTEM_ADMIN DROP CONSTRAINT RD4_SYSTEM_ADMIN_FK_SYSTEM;

ALTER TABLE RD4_APPLICATION_RESULT DROP CONSTRAINT SQL131106123707840;

ALTER TABLE RD4_ROLE DROP CONSTRAINT SQL131025122148450;

ALTER TABLE RD4_SYSTEM DROP CONSTRAINT SQL131025122148430;

ALTER TABLE RD4_NOTIFICATION DROP CONSTRAINT SQL131106171836220;

ALTER TABLE RD4_APPLICATION_STAGE DROP CONSTRAINT SQL131106113620160;

ALTER TABLE RD4_SYSTEM_AUTHORITY DROP CONSTRAINT SQL131025122148720;

ALTER TABLE RD4_APPLICATION DROP CONSTRAINT SQL131105152436960;

ALTER TABLE RD2_ATTRIBUTE DROP CONSTRAINT SQL130823124508700;

ALTER TABLE RD4_SYSTEM_FUNCTION DROP CONSTRAINT SQL131025122148710;

ALTER TABLE RD4_MAIN_AUTHORITY DROP CONSTRAINT SQL131025122148460;

ALTER TABLE RD4_BUG_REPORT DROP CONSTRAINT SQL131025122148750;

ALTER TABLE RD4_TEMPORARY_AUTHORITY DROP CONSTRAINT SQL131025122148550;

ALTER TABLE RD4_TASK_REPORT DROP CONSTRAINT SQL131025122148680;

ALTER TABLE RD4_MISSION DROP CONSTRAINT SQL131108125626870;

ALTER TABLE RD4_UPLOAD_FILE DROP CONSTRAINT SQL131025122148530;

ALTER TABLE RD4_AUTHORITY DROP CONSTRAINT SQL131025122148480;

ALTER TABLE RD4_MISSION_UNIT DROP CONSTRAINT SQL131108125628950;

ALTER TABLE RD4_DEPENDENT_FUNCTION DROP CONSTRAINT SQL131025122148740;

ALTER TABLE RD2_PERSON DROP CONSTRAINT SQL130823124341770;

ALTER TABLE RD4_MISSION_PARTITION DROP CONSTRAINT SQL131108125627930;

ALTER TABLE RD4_DEPENDENT_SYSTEM DROP CONSTRAINT SQL131025122148690;

ALTER TABLE RD4_TASK DROP CONSTRAINT SQL131025122148570;

ALTER TABLE RD4_MESSAGE DROP CONSTRAINT SQL131025122148620;

ALTER TABLE RD4_PARTITION_DEPENDENCY DROP CONSTRAINT SQL131108125647670;

ALTER TABLE RD2_ROLE DROP CONSTRAINT SQL130823124544570;

ALTER TABLE RD4_UNIT_DEPENDENCY DROP CONSTRAINT SQL131108125648690;

ALTER TABLE RD4_USER DROP CONSTRAINT SQL131025122148360;

DROP INDEX SYSTABLES_INDEX2;

DROP INDEX SQL131025122148910;

DROP INDEX SYSTABLEPERMS_INDEX2;

DROP INDEX SYSALIASES_INDEX3;

DROP INDEX SYSCHECKS_INDEX1;

DROP INDEX SQL131108125626870;

DROP INDEX SQL131025122148430;

DROP INDEX SQL131025122148550;

DROP INDEX SYSROLES_INDEX1;

DROP INDEX PK_S_USERSINDEX;

DROP INDEX SQL131108125648690;

DROP INDEX SQL131025122148450;

DROP INDEX SYSFOREIGNKEYS_INDEX2;

DROP INDEX SQL131025122148860;

DROP INDEX SYSKEYS_INDEX1;

DROP INDEX SQL131108125647670;

DROP INDEX SQL131025122148530;

DROP INDEX SYSDEPENDS_INDEX1;

DROP INDEX SQL130823124544570;

DROP INDEX SYSSCHEMAS_INDEX2;

DROP INDEX SYSCOLPERMS_INDEX2;

DROP INDEX SQL131025122149180;

DROP INDEX SYSALIASES_INDEX2;

DROP INDEX SYSROLES_INDEX2;

DROP INDEX SQL131025122148840;

DROP INDEX SQL131025122148850;

DROP INDEX SYSROUTINEPERMS_INDEX3;

DROP INDEX SYSTABLES_INDEX1;

DROP INDEX SYSCOLUMNS_INDEX1;

DROP INDEX SQL130823124341770;

DROP INDEX SQL131025122149240;

DROP INDEX SQL130823124551800;

DROP INDEX SQL131025122148710;

DROP INDEX SYSROLES_INDEX3;

DROP INDEX SYSFOREIGNKEYS_INDEX1;

DROP INDEX SYSTRIGGERS_INDEX3;

DROP INDEX SQL131025122148820;

DROP INDEX SYSALIASES_INDEX1;

DROP INDEX SQL131025122149080;

DROP INDEX SQL131025122148880;

DROP INDEX SQL131025122149090;

DROP INDEX SQL131105152436960;

DROP INDEX SQL131025122148570;

DROP INDEX SQL131108125627930;

DROP INDEX SYSSCHEMAS_INDEX1;

DROP INDEX SYSCOLUMNS_INDEX2;

DROP INDEX SYSDEPENDS_INDEX2;

DROP INDEX SQL131025122149100;

DROP INDEX SYSCOLPERMS_INDEX1;

DROP INDEX SYSVIEWS_INDEX1;

DROP INDEX SYSCONGLOMERATES_INDEX1;

DROP INDEX SQL131025122148620;

DROP INDEX SQL131025122148920;

DROP INDEX SYSCONSTRAINTS_INDEX1;

DROP INDEX SQL131025122148750;

DROP INDEX SYSCONSTRAINTS_INDEX2;

DROP INDEX SYSCONGLOMERATES_INDEX3;

DROP INDEX SQL131108125628950;

DROP INDEX SYSTABLEPERMS_INDEX3;

DROP INDEX SYSROUTINEPERMS_INDEX1;

DROP INDEX SYSTRIGGERS_INDEX1;

DROP INDEX SQL131025122149110;

DROP INDEX SYSFILES_INDEX1;

DROP INDEX SQL131025122148690;

DROP INDEX SQL130823124508700;

DROP INDEX SQL131025122148740;

DROP INDEX SQL131025122148480;

DROP INDEX SQL131025122148360;

DROP INDEX SYSSTATEMENTS_INDEX2;

DROP INDEX SYSCOLPERMS_INDEX3;

DROP INDEX SYSFILES_INDEX2;

DROP INDEX SQL131106171836220;

DROP INDEX SYSSTATISTICS_INDEX1;

DROP INDEX SYSSTATEMENTS_INDEX1;

DROP INDEX PK_S_USERROLEINDEX;

DROP INDEX SQL131025122148800;

DROP INDEX SYSTRIGGERS_INDEX2;

DROP INDEX SQL131025122149200;

DROP INDEX SYSCONSTRAINTS_INDEX3;

DROP INDEX SQL131025122148780;

DROP INDEX SYSTABLEPERMS_INDEX1;

DROP INDEX SYSROUTINEPERMS_INDEX2;

DROP INDEX SQL131025122149170;

DROP INDEX SQL131025122148460;

DROP INDEX PK_S_ROLEINDEX;

DROP INDEX SYSCONGLOMERATES_INDEX2;

DROP INDEX SQL131025122148680;

DROP INDEX SQL131025122148980;

DROP INDEX SQL131025122148720;

DROP INDEX SQL131106123707840;

DROP INDEX SQL131106113620160;

DROP TABLE SYSVIEWS;

DROP TABLE RD4_SYSTEM;

DROP TABLE RD4_TASK_REPORT;

DROP TABLE SYSTABLEPERMS;

DROP TABLE SYSFILES;

DROP TABLE RD4_APPLICATION_RESULT;

DROP TABLE S_USERS;

DROP TABLE SYSCOLPERMS;

DROP TABLE RD4_SYSTEM_FUNCTION;

DROP TABLE SYSSTATISTICS;

DROP TABLE S_USERROLE;

DROP TABLE RD4_SYSTEM_ADMIN;

DROP TABLE SYSTABLES;

DROP TABLE TEST;

DROP TABLE RD4_ROLE;

DROP TABLE RD4_NOTIFICATION;

DROP TABLE SYSCONSTRAINTS;

DROP TABLE RD4_AUTHORITY;

DROP TABLE RD4_USER;

DROP TABLE RD2_PERSON;

DROP TABLE RD4_SYSTEM_AUTHORITY;

DROP TABLE RD4_BUG_REPORT;

DROP TABLE SYSCONGLOMERATES;

DROP TABLE RD4_APPLICATION_STAGE;

DROP TABLE RD4_MESSAGE;

DROP TABLE RD4_TASK;

DROP TABLE SYSROLES;

DROP TABLE RD4_DEPENDENT_FUNCTION;

DROP TABLE RD2_ATTRIBUTE;

DROP TABLE RD4_PARTITION_DEPENDENCY;

DROP TABLE SYSROUTINEPERMS;

DROP TABLE RD4_TEMPORARY_AUTHORITY;

DROP TABLE SYSCHECKS;

DROP TABLE SYSCOLUMNS;

DROP TABLE RD4_MISSION_PARTITION;

DROP TABLE SYSSTATEMENTS;

DROP TABLE RD2_ROLE;

DROP TABLE RD4_DEPENDENT_SYSTEM;

DROP TABLE RD4_APPLICATION;

DROP TABLE SYSALIASES;

DROP TABLE RD4_MISSION_UNIT;

DROP TABLE SYSDUMMY1;

DROP TABLE SYSKEYS;

DROP TABLE RD4_MISSION;

DROP TABLE SYSDEPENDS;

DROP TABLE SYSSCHEMAS;

DROP TABLE SYSFOREIGNKEYS;

DROP TABLE S_ROLE;

DROP TABLE RD4_UNIT_DEPENDENCY;

DROP TABLE SYSTRIGGERS;

DROP TABLE RD4_MAIN_AUTHORITY;

DROP TABLE RD4_UPLOAD_FILE;

CREATE TABLE SYSVIEWS (
		TABLEID CHAR(36) NOT NULL,
		VIEWDEFINITION LONG VARCHAR NOT NULL,
		CHECKOPTION CHAR(1) NOT NULL,
		COMPILATIONSCHEMAID CHAR(36)
	);

CREATE TABLE RD4_SYSTEM (
		SYSTEM_NAME VARCHAR(30) NOT NULL,
		URL VARCHAR(30),
		DESCRIPTION VARCHAR(80),
		WAR_PATH VARCHAR(50),
		DURATION VARCHAR(30),
		STATUS INTEGER
	);

CREATE TABLE RD4_TASK_REPORT (
		ID VARCHAR(50) NOT NULL,
		TASK_ID VARCHAR(50),
		REPORT VARCHAR(1000),
		FILE_ID VARCHAR(50)
	);

CREATE TABLE SYSTABLEPERMS (
		TABLEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		SELECTPRIV CHAR(1) NOT NULL,
		DELETEPRIV CHAR(1) NOT NULL,
		INSERTPRIV CHAR(1) NOT NULL,
		UPDATEPRIV CHAR(1) NOT NULL,
		REFERENCESPRIV CHAR(1) NOT NULL,
		TRIGGERPRIV CHAR(1) NOT NULL
	);

CREATE TABLE SYSFILES (
		FILEID CHAR(36) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		FILENAME VARCHAR(128) NOT NULL,
		GENERATIONID BIGINT NOT NULL
	);

CREATE TABLE RD4_APPLICATION_RESULT (
		ID VARCHAR(50) NOT NULL,
		APPLICATION_CLASS_ID VARCHAR(50),
		TYPE INTEGER,
		TITLE VARCHAR(250),
		BODY VARCHAR(2000),
		TIME BIGINT,
		FILE_ID VARCHAR(50),
		DATA1 VARCHAR(500),
		DATA2 VARCHAR(500),
		DATA3 VARCHAR(500),
		STATUE INTEGER
	);

CREATE TABLE S_USERS (
		ID VARCHAR(20),
		PASSWORD VARCHAR(50),
		FIRSTNAME VARCHAR(20),
		LASTNAME VARCHAR(20),
		EMAIL VARCHAR(100),
		LANGUAGE INTEGER,
		DICTIONARY_VALUE_KEY VARCHAR(10),
		PRIMARY_OFFICE_SEQ INTEGER
	);

CREATE TABLE SYSCOLPERMS (
		COLPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		COLUMNS null NOT NULL
	);

CREATE TABLE RD4_SYSTEM_FUNCTION (
		ID VARCHAR(50) NOT NULL,
		SYSTEM_NAME VARCHAR(30),
		FUNCTION_NAME VARCHAR(30),
		DESCRIPTION VARCHAR(100)
	);

CREATE TABLE SYSSTATISTICS (
		STATID CHAR(36) NOT NULL,
		REFERENCEID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		COLCOUNT INTEGER NOT NULL,
		STATISTICS null NOT NULL
	);

CREATE TABLE S_USERROLE (
		ID VARCHAR(20),
		ROLENAME VARCHAR(30)
	);

CREATE TABLE RD4_SYSTEM_ADMIN (
		ID VARCHAR(50),
		USER_NAME VARCHAR(30),
		SYSTEM_NAME VARCHAR(30),
		CONDITION VARCHAR(50),
		IS_TEMPORARY INTEGER,
		ORIGIN_ADMIN VARCHAR(50)
	);

CREATE TABLE SYSTABLES (
		TABLEID CHAR(36) NOT NULL,
		TABLENAME VARCHAR(128) NOT NULL,
		TABLETYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		LOCKGRANULARITY CHAR(1) NOT NULL
	);

CREATE TABLE TEST (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NAME VARCHAR(30),
		ROLEID INTEGER,
		VALUE VARCHAR(50)
	);

CREATE TABLE RD4_ROLE (
		ROLE_NAME VARCHAR(30) NOT NULL,
		DESCRIPTION VARCHAR(100)
	);

CREATE TABLE RD4_NOTIFICATION (
		ID VARCHAR(50) NOT NULL,
		RECIEVER_NAME VARCHAR(30),
		TYPE INTEGER,
		TITLE VARCHAR(50),
		BODY VARCHAR(500),
		DATA VARCHAR(200),
		TIME BIGINT,
		FILE_ID VARCHAR(50),
		STATUE INTEGER,
		LINK VARCHAR(100)
	);

CREATE TABLE SYSCONSTRAINTS (
		CONSTRAINTID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONSTRAINTNAME VARCHAR(128) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		STATE CHAR(1) NOT NULL,
		REFERENCECOUNT INTEGER NOT NULL
	);

CREATE TABLE RD4_AUTHORITY (
		AUTHORITY_NAME VARCHAR(30) NOT NULL
	);

CREATE TABLE RD4_USER (
		USER_NAME VARCHAR(30) NOT NULL,
		PASSWORD VARCHAR(50),
		ROLE_NAME VARCHAR(30),
		EXPIRE_TIME BIGINT,
		REAL_NAME VARCHAR(30),
		IDENTITY_NUMBER VARCHAR(30),
		DESCRIPTION VARCHAR(200),
		DEPARTMENT VARCHAR(30),
		CONDITION VARCHAR(50)
	);

CREATE TABLE RD2_PERSON (
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 15),
		NAME VARCHAR(30),
		ROLEID INTEGER,
		VALUE VARCHAR(50)
	);

CREATE TABLE RD4_SYSTEM_AUTHORITY (
		ID VARCHAR(50) NOT NULL,
		ROLE_NAME VARCHAR(30),
		SYSTEM_FUNCTION_ID VARCHAR(50)
	);

CREATE TABLE RD4_BUG_REPORT (
		ID VARCHAR(50) NOT NULL,
		SYSTEM_NAME VARCHAR(30),
		FOUNDER_NAME VARCHAR(30),
		REPORT VARCHAR(250),
		FIX_REPORT VARCHAR(250),
		ISFIXED INTEGER,
		FILE_ID VARCHAR(50)
	);

CREATE TABLE SYSCONGLOMERATES (
		SCHEMAID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONGLOMERATENUMBER BIGINT NOT NULL,
		CONGLOMERATENAME VARCHAR(128),
		ISINDEX null NOT NULL,
		DESCRIPTOR null,
		ISCONSTRAINT null,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE RD4_APPLICATION_STAGE (
		ID VARCHAR(50) NOT NULL,
		NAME VARCHAR(200),
		SERIAL INTEGER,
		APPLICATION_CLASS_ID VARCHAR(50),
		DEALER_NAME VARCHAR(30),
		DATA VARCHAR(1000),
		FILE_ID VARCHAR(50),
		STATUS INTEGER,
		COMMENTS VARCHAR(1000)
	);

CREATE TABLE RD4_MESSAGE (
		ID VARCHAR(50) NOT NULL,
		SENDER_NAME VARCHAR(30),
		RECIEVER_NAME VARCHAR(30),
		TITLE VARCHAR(50),
		BODY VARCHAR(10000),
		TIME BIGINT,
		FILE_ID VARCHAR(50),
		STATUE INTEGER
	);

CREATE TABLE RD4_TASK (
		ID VARCHAR(50) NOT NULL,
		CREATOR_NAME VARCHAR(30),
		OWNER_NAME VARCHAR(30),
		TYPE VARCHAR(20),
		TITLE VARCHAR(50),
		DESCRIPTION VARCHAR(300),
		START_TIME BIGINT,
		END_TIME BIGINT,
		STATUE INTEGER,
		DATA VARCHAR(50),
		FILE_ID VARCHAR(50)
	);

CREATE TABLE SYSROLES (
		UUID CHAR(36) NOT NULL,
		ROLEID VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		WITHADMINOPTION CHAR(1) NOT NULL,
		ISDEF CHAR(1) NOT NULL
	);

CREATE TABLE RD4_DEPENDENT_FUNCTION (
		ID VARCHAR(50) NOT NULL,
		TYPE VARCHAR(30),
		TARGET_ID VARCHAR(50),
		FUNCTION_ID VARCHAR(50)
	);

CREATE TABLE RD2_ATTRIBUTE (
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 25),
		NAME VARCHAR(30),
		ATTRIBUTE_TYPE VARCHAR(30),
		TYPE_INFO VARCHAR(30),
		VALUE_TYPE VARCHAR(30)
	);

CREATE TABLE RD4_PARTITION_DEPENDENCY (
		ID VARCHAR(50) NOT NULL,
		BELONGED_MISSION_ID VARCHAR(50),
		PRE_PARTITION_ID VARCHAR(50),
		POST_PARTITION_ID VARCHAR(50)
	);

CREATE TABLE SYSROUTINEPERMS (
		ROUTINEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		ALIASID CHAR(36) NOT NULL,
		GRANTOPTION CHAR(1) NOT NULL
	);

CREATE TABLE RD4_TEMPORARY_AUTHORITY (
		ID VARCHAR(50) NOT NULL,
		USER_NAME VARCHAR(30),
		SYSTEM_FUNCTION_ID VARCHAR(50),
		DESCRIPTION VARCHAR(100),
		EXPIRE_TIME BIGINT
	);

CREATE TABLE SYSCHECKS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CHECKDEFINITION LONG VARCHAR NOT NULL,
		REFERENCEDCOLUMNS null NOT NULL
	);

CREATE TABLE SYSCOLUMNS (
		REFERENCEID CHAR(36) NOT NULL,
		COLUMNNAME VARCHAR(128) NOT NULL,
		COLUMNNUMBER INTEGER NOT NULL,
		COLUMNDATATYPE null NOT NULL,
		COLUMNDEFAULT null,
		COLUMNDEFAULTID CHAR(36),
		AUTOINCREMENTVALUE BIGINT,
		AUTOINCREMENTSTART BIGINT,
		AUTOINCREMENTINC BIGINT
	);

CREATE TABLE RD4_MISSION_PARTITION (
		ID VARCHAR(50) NOT NULL,
		MISSION_ID VARCHAR(50),
		LEADER_NAME VARCHAR(30),
		TITLE VARCHAR(50),
		DESCRIPTION VARCHAR(300),
		FILE_ID VARCHAR(50),
		PROGRESS INTEGER
	);

CREATE TABLE SYSSTATEMENTS (
		STMTID CHAR(36) NOT NULL,
		STMTNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		TEXT LONG VARCHAR NOT NULL,
		LASTCOMPILED TIMESTAMP,
		COMPILATIONSCHEMAID CHAR(36),
		USINGTEXT LONG VARCHAR
	);

CREATE TABLE RD2_ROLE (
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 25),
		NAME VARCHAR(30),
		ATTRIBUTE1 VARCHAR(30)
	);

CREATE TABLE RD4_DEPENDENT_SYSTEM (
		ID VARCHAR(50) NOT NULL,
		TYPE INTEGER,
		TARGET_ID VARCHAR(50),
		SYSTEM_NAME VARCHAR(30)
	);

CREATE TABLE RD4_APPLICATION (
		ID VARCHAR(50) NOT NULL,
		SENDER_NAME VARCHAR(30),
		RECIEVER_NAME VARCHAR(30),
		TYPE INTEGER,
		TITLE VARCHAR(50),
		BODY VARCHAR(500),
		DATA VARCHAR(200),
		TIME BIGINT,
		FILE_ID VARCHAR(50),
		STATUE INTEGER,
		CLASS VARCHAR(50),
		STAGE INTEGER
	);

CREATE TABLE SYSALIASES (
		ALIASID CHAR(36) NOT NULL,
		ALIAS VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36),
		JAVACLASSNAME LONG VARCHAR NOT NULL,
		ALIASTYPE CHAR(1) NOT NULL,
		NAMESPACE CHAR(1) NOT NULL,
		SYSTEMALIAS null NOT NULL,
		ALIASINFO null,
		SPECIFICNAME VARCHAR(128) NOT NULL
	);

CREATE TABLE RD4_MISSION_UNIT (
		ID VARCHAR(50) NOT NULL,
		PARTITION_ID VARCHAR(50),
		LEADER_NAME VARCHAR(30),
		TITLE VARCHAR(50),
		DESCRIPTION VARCHAR(300),
		FILE_ID VARCHAR(50),
		PROGRESS INTEGER
	);

CREATE TABLE SYSDUMMY1 (
		IBMREQD CHAR(1)
	);

CREATE TABLE SYSKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE RD4_MISSION (
		ID VARCHAR(50) NOT NULL,
		CREATOR_NAME VARCHAR(30),
		LEADER_NAME VARCHAR(30),
		TITLE VARCHAR(50),
		DESCRIPTION VARCHAR(300),
		FILE_ID VARCHAR(50),
		PROGRESS INTEGER
	);

CREATE TABLE SYSDEPENDS (
		DEPENDENTID CHAR(36) NOT NULL,
		DEPENDENTFINDER null NOT NULL,
		PROVIDERID CHAR(36) NOT NULL,
		PROVIDERFINDER null NOT NULL
	);

CREATE TABLE SYSSCHEMAS (
		SCHEMAID CHAR(36) NOT NULL,
		SCHEMANAME VARCHAR(128) NOT NULL,
		AUTHORIZATIONID VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSFOREIGNKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL,
		KEYCONSTRAINTID CHAR(36) NOT NULL,
		DELETERULE CHAR(1) NOT NULL,
		UPDATERULE CHAR(1) NOT NULL
	);

CREATE TABLE S_ROLE (
		ROLE VARCHAR(10)
	);

CREATE TABLE RD4_UNIT_DEPENDENCY (
		ID VARCHAR(50) NOT NULL,
		BELONGED_PARTITION_ID VARCHAR(50),
		PRE_UNIT_ID VARCHAR(50),
		POST_UNIT_ID VARCHAR(50)
	);

CREATE TABLE SYSTRIGGERS (
		TRIGGERID CHAR(36) NOT NULL,
		TRIGGERNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		EVENT CHAR(1) NOT NULL,
		FIRINGTIME CHAR(1) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		STATE CHAR(1) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		WHENSTMTID CHAR(36),
		ACTIONSTMTID CHAR(36),
		REFERENCEDCOLUMNS null,
		TRIGGERDEFINITION LONG VARCHAR,
		REFERENCINGOLD null,
		REFERENCINGNEW null,
		OLDREFERENCINGNAME VARCHAR(128),
		NEWREFERENCINGNAME VARCHAR(128)
	);

CREATE TABLE RD4_MAIN_AUTHORITY (
		ID VARCHAR(50) NOT NULL,
		USER_NAME VARCHAR(30) NOT NULL,
		AUTHORITY_NAME VARCHAR(30) NOT NULL
	);

CREATE TABLE RD4_UPLOAD_FILE (
		ID VARCHAR(50) NOT NULL,
		UPLOADER_NAME VARCHAR(30),
		FILE_PATH VARCHAR(250),
		FILE_NAME VARCHAR(250)
	);

CREATE UNIQUE INDEX SYSTABLES_INDEX2 ON SYSTABLES (TABLEID ASC);

CREATE INDEX SQL131025122148910 ON RD4_MESSAGE (SENDER_NAME ASC);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX2 ON SYSTABLEPERMS (TABLEPERMSID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX3 ON SYSALIASES (SCHEMAID ASC, SPECIFICNAME ASC);

CREATE UNIQUE INDEX SYSCHECKS_INDEX1 ON SYSCHECKS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SQL131108125626870 ON RD4_MISSION (ID ASC);

CREATE UNIQUE INDEX SQL131025122148430 ON RD4_SYSTEM (SYSTEM_NAME ASC);

CREATE UNIQUE INDEX SQL131025122148550 ON RD4_TEMPORARY_AUTHORITY (ID ASC);

CREATE UNIQUE INDEX SYSROLES_INDEX1 ON SYSROLES (ROLEID ASC, GRANTEE ASC, GRANTOR ASC);

CREATE INDEX PK_S_USERSINDEX ON S_USERS (ID ASC);

CREATE UNIQUE INDEX SQL131108125648690 ON RD4_UNIT_DEPENDENCY (ID ASC);

CREATE UNIQUE INDEX SQL131025122148450 ON RD4_ROLE (ROLE_NAME ASC);

CREATE INDEX SYSFOREIGNKEYS_INDEX2 ON SYSFOREIGNKEYS (KEYCONSTRAINTID ASC);

CREATE INDEX SQL131025122148860 ON RD4_SYSTEM_AUTHORITY (SYSTEM_FUNCTION_ID ASC);

CREATE UNIQUE INDEX SYSKEYS_INDEX1 ON SYSKEYS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SQL131108125647670 ON RD4_PARTITION_DEPENDENCY (ID ASC);

CREATE UNIQUE INDEX SQL131025122148530 ON RD4_UPLOAD_FILE (ID ASC);

CREATE INDEX SYSDEPENDS_INDEX1 ON SYSDEPENDS (DEPENDENTID ASC);

CREATE UNIQUE INDEX SQL130823124544570 ON RD2_ROLE (ID ASC);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX2 ON SYSSCHEMAS (SCHEMAID ASC);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX2 ON SYSCOLPERMS (COLPERMSID ASC);

CREATE INDEX SQL131025122149180 ON RD4_TEMPORARY_AUTHORITY (USER_NAME ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX2 ON SYSALIASES (ALIASID ASC);

CREATE INDEX SYSROLES_INDEX2 ON SYSROLES (ROLEID ASC, ISDEF ASC);

CREATE INDEX SQL131025122148840 ON RD4_SYSTEM_FUNCTION (SYSTEM_NAME ASC);

CREATE INDEX SQL131025122148850 ON RD4_SYSTEM_AUTHORITY (ROLE_NAME ASC);

CREATE INDEX SYSROUTINEPERMS_INDEX3 ON SYSROUTINEPERMS (ALIASID ASC);

CREATE UNIQUE INDEX SYSTABLES_INDEX1 ON SYSTABLES (TABLENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSCOLUMNS_INDEX1 ON SYSCOLUMNS (REFERENCEID ASC, COLUMNNAME ASC);

CREATE UNIQUE INDEX SQL130823124341770 ON RD2_PERSON (ID ASC);

CREATE INDEX SQL131025122149240 ON RD4_TASK (CREATOR_NAME ASC);

CREATE INDEX SQL130823124551800 ON RD2_PERSON (ROLEID ASC);

CREATE UNIQUE INDEX SQL131025122148710 ON RD4_SYSTEM_FUNCTION (ID ASC);

CREATE UNIQUE INDEX SYSROLES_INDEX3 ON SYSROLES (UUID ASC);

CREATE UNIQUE INDEX SYSFOREIGNKEYS_INDEX1 ON SYSFOREIGNKEYS (CONSTRAINTID ASC);

CREATE INDEX SYSTRIGGERS_INDEX3 ON SYSTRIGGERS (TABLEID ASC, CREATIONTIMESTAMP ASC);

CREATE INDEX SQL131025122148820 ON RD4_TEMPORARY_AUTHORITY (SYSTEM_FUNCTION_ID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX1 ON SYSALIASES (SCHEMAID ASC, ALIAS ASC, NAMESPACE ASC);

CREATE INDEX SQL131025122149080 ON RD4_SYSTEM_ADMIN (USER_NAME ASC);

CREATE INDEX SQL131025122148880 ON RD4_DEPENDENT_SYSTEM (SYSTEM_NAME ASC);

CREATE INDEX SQL131025122149090 ON RD4_SYSTEM_ADMIN (SYSTEM_NAME ASC);

CREATE UNIQUE INDEX SQL131105152436960 ON RD4_APPLICATION (ID ASC);

CREATE UNIQUE INDEX SQL131025122148570 ON RD4_TASK (ID ASC);

CREATE UNIQUE INDEX SQL131108125627930 ON RD4_MISSION_PARTITION (ID ASC);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX1 ON SYSSCHEMAS (SCHEMANAME ASC);

CREATE INDEX SYSCOLUMNS_INDEX2 ON SYSCOLUMNS (COLUMNDEFAULTID ASC);

CREATE INDEX SYSDEPENDS_INDEX2 ON SYSDEPENDS (PROVIDERID ASC);

CREATE INDEX SQL131025122149100 ON RD4_MAIN_AUTHORITY (AUTHORITY_NAME ASC);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX1 ON SYSCOLPERMS (GRANTEE ASC, TABLEID ASC, TYPE ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSVIEWS_INDEX1 ON SYSVIEWS (TABLEID ASC);

CREATE INDEX SYSCONGLOMERATES_INDEX1 ON SYSCONGLOMERATES (CONGLOMERATEID ASC);

CREATE UNIQUE INDEX SQL131025122148620 ON RD4_MESSAGE (ID ASC);

CREATE INDEX SQL131025122148920 ON RD4_MESSAGE (RECIEVER_NAME ASC);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX1 ON SYSCONSTRAINTS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SQL131025122148750 ON RD4_BUG_REPORT (ID ASC);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX2 ON SYSCONSTRAINTS (CONSTRAINTNAME ASC, SCHEMAID ASC);

CREATE INDEX SYSCONGLOMERATES_INDEX3 ON SYSCONGLOMERATES (TABLEID ASC);

CREATE UNIQUE INDEX SQL131108125628950 ON RD4_MISSION_UNIT (ID ASC);

CREATE INDEX SYSTABLEPERMS_INDEX3 ON SYSTABLEPERMS (TABLEID ASC);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX1 ON SYSROUTINEPERMS (GRANTEE ASC, ALIASID ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX1 ON SYSTRIGGERS (TRIGGERID ASC);

CREATE INDEX SQL131025122149110 ON RD4_USER (ROLE_NAME ASC);

CREATE UNIQUE INDEX SYSFILES_INDEX1 ON SYSFILES (FILENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SQL131025122148690 ON RD4_DEPENDENT_SYSTEM (ID ASC);

CREATE UNIQUE INDEX SQL130823124508700 ON RD2_ATTRIBUTE (ID ASC);

CREATE UNIQUE INDEX SQL131025122148740 ON RD4_DEPENDENT_FUNCTION (ID ASC);

CREATE UNIQUE INDEX SQL131025122148480 ON RD4_AUTHORITY (AUTHORITY_NAME ASC);

CREATE UNIQUE INDEX SQL131025122148360 ON RD4_USER (USER_NAME ASC);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX2 ON SYSSTATEMENTS (STMTNAME ASC, SCHEMAID ASC);

CREATE INDEX SYSCOLPERMS_INDEX3 ON SYSCOLPERMS (TABLEID ASC);

CREATE UNIQUE INDEX SYSFILES_INDEX2 ON SYSFILES (FILEID ASC);

CREATE UNIQUE INDEX SQL131106171836220 ON RD4_NOTIFICATION (ID ASC);

CREATE INDEX SYSSTATISTICS_INDEX1 ON SYSSTATISTICS (TABLEID ASC, REFERENCEID ASC);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX1 ON SYSSTATEMENTS (STMTID ASC);

CREATE INDEX PK_S_USERROLEINDEX ON S_USERROLE (ID ASC, ROLENAME ASC);

CREATE INDEX SQL131025122148800 ON RD4_BUG_REPORT (FOUNDER_NAME ASC);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX2 ON SYSTRIGGERS (TRIGGERNAME ASC, SCHEMAID ASC);

CREATE INDEX SQL131025122149200 ON RD4_TASK (OWNER_NAME ASC);

CREATE INDEX SYSCONSTRAINTS_INDEX3 ON SYSCONSTRAINTS (TABLEID ASC);

CREATE INDEX SQL131025122148780 ON RD4_BUG_REPORT (SYSTEM_NAME ASC);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX1 ON SYSTABLEPERMS (GRANTEE ASC, TABLEID ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX2 ON SYSROUTINEPERMS (ROUTINEPERMSID ASC);

CREATE INDEX SQL131025122149170 ON RD4_MAIN_AUTHORITY (USER_NAME ASC);

CREATE UNIQUE INDEX SQL131025122148460 ON RD4_MAIN_AUTHORITY (ID ASC);

CREATE INDEX PK_S_ROLEINDEX ON S_ROLE (ROLE ASC);

CREATE UNIQUE INDEX SYSCONGLOMERATES_INDEX2 ON SYSCONGLOMERATES (CONGLOMERATENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SQL131025122148680 ON RD4_TASK_REPORT (ID ASC);

CREATE INDEX SQL131025122148980 ON RD4_UPLOAD_FILE (UPLOADER_NAME ASC);

CREATE UNIQUE INDEX SQL131025122148720 ON RD4_SYSTEM_AUTHORITY (ID ASC);

CREATE UNIQUE INDEX SQL131106123707840 ON RD4_APPLICATION_RESULT (ID ASC);

CREATE UNIQUE INDEX SQL131106113620160 ON RD4_APPLICATION_STAGE (ID ASC);

ALTER TABLE RD4_APPLICATION_RESULT ADD CONSTRAINT SQL131106123707840 PRIMARY KEY (ID);

ALTER TABLE RD4_ROLE ADD CONSTRAINT SQL131025122148450 PRIMARY KEY (ROLE_NAME);

ALTER TABLE RD4_SYSTEM ADD CONSTRAINT SQL131025122148430 PRIMARY KEY (SYSTEM_NAME);

ALTER TABLE RD4_NOTIFICATION ADD CONSTRAINT SQL131106171836220 PRIMARY KEY (ID);

ALTER TABLE RD4_APPLICATION_STAGE ADD CONSTRAINT SQL131106113620160 PRIMARY KEY (ID);

ALTER TABLE RD4_SYSTEM_AUTHORITY ADD CONSTRAINT SQL131025122148720 PRIMARY KEY (ID);

ALTER TABLE RD4_APPLICATION ADD CONSTRAINT SQL131105152436960 PRIMARY KEY (ID);

ALTER TABLE RD2_ATTRIBUTE ADD CONSTRAINT SQL130823124508700 PRIMARY KEY (ID);

ALTER TABLE RD4_SYSTEM_FUNCTION ADD CONSTRAINT SQL131025122148710 PRIMARY KEY (ID);

ALTER TABLE RD4_MAIN_AUTHORITY ADD CONSTRAINT SQL131025122148460 PRIMARY KEY (ID);

ALTER TABLE RD4_BUG_REPORT ADD CONSTRAINT SQL131025122148750 PRIMARY KEY (ID);

ALTER TABLE RD4_TEMPORARY_AUTHORITY ADD CONSTRAINT SQL131025122148550 PRIMARY KEY (ID);

ALTER TABLE RD4_TASK_REPORT ADD CONSTRAINT SQL131025122148680 PRIMARY KEY (ID);

ALTER TABLE RD4_MISSION ADD CONSTRAINT SQL131108125626870 PRIMARY KEY (ID);

ALTER TABLE RD4_UPLOAD_FILE ADD CONSTRAINT SQL131025122148530 PRIMARY KEY (ID);

ALTER TABLE RD4_AUTHORITY ADD CONSTRAINT SQL131025122148480 PRIMARY KEY (AUTHORITY_NAME);

ALTER TABLE RD4_MISSION_UNIT ADD CONSTRAINT SQL131108125628950 PRIMARY KEY (ID);

ALTER TABLE RD4_DEPENDENT_FUNCTION ADD CONSTRAINT SQL131025122148740 PRIMARY KEY (ID);

ALTER TABLE RD2_PERSON ADD CONSTRAINT SQL130823124341770 PRIMARY KEY (ID);

ALTER TABLE RD4_MISSION_PARTITION ADD CONSTRAINT SQL131108125627930 PRIMARY KEY (ID);

ALTER TABLE RD4_DEPENDENT_SYSTEM ADD CONSTRAINT SQL131025122148690 PRIMARY KEY (ID);

ALTER TABLE RD4_TASK ADD CONSTRAINT SQL131025122148570 PRIMARY KEY (ID);

ALTER TABLE RD4_MESSAGE ADD CONSTRAINT SQL131025122148620 PRIMARY KEY (ID);

ALTER TABLE RD4_PARTITION_DEPENDENCY ADD CONSTRAINT SQL131108125647670 PRIMARY KEY (ID);

ALTER TABLE RD2_ROLE ADD CONSTRAINT SQL130823124544570 PRIMARY KEY (ID);

ALTER TABLE RD4_UNIT_DEPENDENCY ADD CONSTRAINT SQL131108125648690 PRIMARY KEY (ID);

ALTER TABLE RD4_USER ADD CONSTRAINT SQL131025122148360 PRIMARY KEY (USER_NAME);

ALTER TABLE RD4_TEMPORARY_AUTHORITY ADD CONSTRAINT RD4_TEMPORARY_AUTHORITY_FK_USER FOREIGN KEY (USER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_MAIN_AUTHORITY ADD CONSTRAINT RD4_MAIN_AUTHORITY_FK_USER FOREIGN KEY (USER_NAME)
	REFERENCES RD4_USER (USER_NAME)
	ON DELETE CASCADE;

ALTER TABLE RD4_SYSTEM_AUTHORITY ADD CONSTRAINT RD4_SYSTEM_AUTHORITY_FK_SYSTEM_FUNCTION FOREIGN KEY (SYSTEM_FUNCTION_ID)
	REFERENCES RD4_SYSTEM_FUNCTION (ID);

ALTER TABLE RD4_SYSTEM_ADMIN ADD CONSTRAINT RD4_SYSTEM_ADMIN_FK_USER FOREIGN KEY (USER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_SYSTEM_AUTHORITY ADD CONSTRAINT RD4_SYSTEM_AUTHORITY_FK_ROLE FOREIGN KEY (ROLE_NAME)
	REFERENCES RD4_ROLE (ROLE_NAME);

ALTER TABLE RD4_MESSAGE ADD CONSTRAINT RD4_MESSAGE_FK_RECIEVER FOREIGN KEY (RECIEVER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_USER ADD CONSTRAINT RD4_USER_FK_ROLE FOREIGN KEY (ROLE_NAME)
	REFERENCES RD4_ROLE (ROLE_NAME);

ALTER TABLE RD4_TASK ADD CONSTRAINT RD4_TASK_FK_USER FOREIGN KEY (OWNER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_BUG_REPORT ADD CONSTRAINT RD4_BUG_REPORT_FK_SYSTEM FOREIGN KEY (SYSTEM_NAME)
	REFERENCES RD4_SYSTEM (SYSTEM_NAME);

ALTER TABLE RD4_BUG_REPORT ADD CONSTRAINT RD4_BUG_REPORT_FK_USER FOREIGN KEY (FOUNDER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_TASK ADD CONSTRAINT RD4_TASK_FK_CREATOR FOREIGN KEY (CREATOR_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_UPLOAD_FILE ADD CONSTRAINT RD4_UPLOAD_FILE_FK_USER FOREIGN KEY (UPLOADER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_DEPENDENT_SYSTEM ADD CONSTRAINT RD4_DEPENDENT_SYSTEM_FK_SYSTEM FOREIGN KEY (SYSTEM_NAME)
	REFERENCES RD4_SYSTEM (SYSTEM_NAME);

ALTER TABLE RD4_MESSAGE ADD CONSTRAINT RD4_MESSAGE_FK_SENDER FOREIGN KEY (SENDER_NAME)
	REFERENCES RD4_USER (USER_NAME);

ALTER TABLE RD4_MAIN_AUTHORITY ADD CONSTRAINT RD4_MAIN_AUTHORITY_FK_AUTHORITY FOREIGN KEY (AUTHORITY_NAME)
	REFERENCES RD4_AUTHORITY (AUTHORITY_NAME);

ALTER TABLE RD4_TEMPORARY_AUTHORITY ADD CONSTRAINT RD4_TEMPORARY_AUTHORITY_FK_FUNCTION FOREIGN KEY (SYSTEM_FUNCTION_ID)
	REFERENCES RD4_SYSTEM_FUNCTION (ID);

ALTER TABLE RD2_PERSON ADD CONSTRAINT PERSON_FK_ROLE FOREIGN KEY (ROLEID)
	REFERENCES RD2_ROLE (ID);

ALTER TABLE RD4_SYSTEM_FUNCTION ADD CONSTRAINT RD4_SYSTEM_FUNCTION_FK_SYSTEM FOREIGN KEY (SYSTEM_NAME)
	REFERENCES RD4_SYSTEM (SYSTEM_NAME);

ALTER TABLE RD4_SYSTEM_ADMIN ADD CONSTRAINT RD4_SYSTEM_ADMIN_FK_SYSTEM FOREIGN KEY (SYSTEM_NAME)
	REFERENCES RD4_SYSTEM (SYSTEM_NAME);

